### ISSUE TITLE
Creating complex and rational numbers from string

### ISSUE THREAD

**Issue by mossadal** [chippyash/Strong-Type#1]
It seems to me as if `RationalTypeFactory::fromString()` and `ComplexTypeFactory::fromString()` are too strict regarding the string representations that are allowed.

Each of

```
RationalTypeFactory::fromString('1');
ComplexTypeFactory::fromString('1+i');
ComplexTypeFactory::fromString('1-i');
ComplexTypeFactory::fromString('2i');
ComplexTypeFactory::fromString('2');
```

throw an `InvalidArgumentException`. It seems unreasonably strict to require (especially when working with data coming from user input) that these numbers have to be entered as `1/1`, `1+1i`, `1-1i`, `0+2i` and `2+0i` respectively.

I can create a PR allowing for more lenient handling of such inputs, but before I do so, I'd like your opinion on how do you want things to be.

**Comment by chippyash** [comment]
Hi, as the only arbiter of fromString() being called is whether the incoming parameter is in fact a string, then if it aids lib users by allowing such leniency, it is an improvement.  Happy to accept a PR to that effect. Please use the current master branch as source.

Many thanks.
